### PR TITLE
Plot, Fix Param Choice Error: Take 2

### PR DESCRIPTION
**Pull request by arnavs**

### CODE REVIEW

**Comment by jstac** [comment]
@ArnavSood This has merge conflicts again and I have no idea why.  It's very odd. Could you please just email me the new version?  I'll close this PR again.

**Comment by cc7768** [comment]
@ArnavSood You might think about rebasing your fork against the main repository hosted by @jstac.

The issues are probably coming from the fact that the two of you have different git histories. I don't know how many differences you have, but there are some easy (and some harder) ways of getting these histories to match up again.

**Comment by arnavs** [comment]
@jstac Sounds good. I'll send that over to you right now.

@cc7768 Also sounds good -- with the slight proviso that I don't know how. I'll give it a shot over the break, and let you know how it goes.

**Comment by cc7768** [comment]
@ArnavSood Feel free to shoot me an email if you have questions.

**Pull request closed without merging**
